---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 6d4128d781af61347c595729ab27c122af5078e6
    prometheus.io/port: "9779"
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/vinnsl-nn-ui/vinnsl-nn-ui-deploy
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    fabric8.io/scm-tag: HEAD
  labels:
    testProject: vinnsl-ui
    app: vinnsl-nn-ui-deploy
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: at.ac.univie.a0908270.nncloud
  name: vinnsl-ui
spec:
  ports:
  - name: radan-http
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: vinnsl-nn-ui-deploy
    provider: fabric8
    group: at.ac.univie.a0908270.nncloud
  type: NodePort
